/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cenaFilosofos;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hertz676
 */
public class ventanaFilosofos extends javax.swing.JFrame {

    public ventanaFilosofos() {
        initComponents();
        this.setTitle("Cena de filosofos");
        this.setLocationRelativeTo(null);//Establecemos la ventana en el centro
        setImageLabel(fondo, "/home/hertz676/NetBeansProjects/CenaDeFilosofos/src/Imagenes/fondo.JPG");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        Cenar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -40, 340, 320));
        jPanel1.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 340, 320));
        jPanel1.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 340, 320));
        jPanel1.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 340, 320));
        jPanel1.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 340, 320));

        Cenar.setText("Iniciar cena");
        Cenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenarActionPerformed(evt);
            }
        });
        jPanel1.add(Cenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.JPG"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenarActionPerformed
        // TODO add your handling code here:
        Mesa m = new Mesa(5, f1, f2, f3, f4, f5);
        /*for (int i = 1; i <= 5; i++) {
            Filosofo f = new Filosofo(m, i, f1, f2, f3, f4, f5);
            f.start();
        }*/
        
        Thread filo1 = new Thread(new Filosofo(m,1,f1, f2, f3, f4, f5));
        Thread filo2 = new Thread(new Filosofo(m,2,f1, f2, f3, f4, f5));
        Thread filo3 = new Thread(new Filosofo(m,3,f1, f2, f3, f4, f5));
        Thread filo4 = new Thread(new Filosofo(m,4,f1, f2, f3, f4, f5));
        Thread filo5 = new Thread(new Filosofo(m,5,f1, f2, f3, f4, f5));
        
        filo1.start();
        filo2.start();
        filo3.start();
        filo4.start();
        filo5.start();
        
    }//GEN-LAST:event_CenarActionPerformed

    public void setImageLabel(JLabel fondobg, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(fondobg.getWidth(), fondobg.getHeight(), Image.SCALE_DEFAULT)
        );
        fondobg.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cenar;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
