package proyecto;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Cocina extends javax.swing.JFrame {

    int contadorProductores = 0;
    int contadorConsumidores = 0;
    ChefCliente m;

    public Cocina() {
        initComponents();
        this.setLocationRelativeTo(this);
        setImageLabel(chef1, "/home/hertz676/NetBeansProjects/Productor-consumidor_Paralela/src/imagenes/Productor.jpg");
        acomodarMesa(mesa, "/home/hertz676/NetBeansProjects/Productor-consumidor_Paralela/src/imagenes/recursoCompartido.png");
        consumidor(joey, "/home/hertz676/NetBeansProjects/Productor-consumidor_Paralela/src/imagenes/Consumidor.jpg");
        this.setTitle("Productor-consumidor");
        this.setLocationRelativeTo(null);//Establecemos la ventana en el centro
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pizza1 = new javax.swing.JLabel();
        pizza2 = new javax.swing.JLabel();
        pizza3 = new javax.swing.JLabel();
        pizza4 = new javax.swing.JLabel();
        pizza5 = new javax.swing.JLabel();
        pizza6 = new javax.swing.JLabel();
        pizza7 = new javax.swing.JLabel();
        pizza8 = new javax.swing.JLabel();
        pizza0 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        chef2 = new javax.swing.JLabel();
        chef3 = new javax.swing.JLabel();
        chef4 = new javax.swing.JLabel();
        chef5 = new javax.swing.JLabel();
        estadoChef = new javax.swing.JLabel();
        chefdurmiendo = new javax.swing.JLabel();
        estadoJoey = new javax.swing.JLabel();
        botonInicio = new javax.swing.JButton();
        chef1 = new javax.swing.JLabel();
        joey = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, 40));
        jPanel1.add(pizza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 50, 40));
        jPanel1.add(pizza3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 50, 40));
        jPanel1.add(pizza4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 50, 40));
        jPanel1.add(pizza5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 50, 40));
        jPanel1.add(pizza6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 50, 40));
        jPanel1.add(pizza7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 50, 40));
        jPanel1.add(pizza8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 50, 40));
        jPanel1.add(pizza0, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 130));
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 120, 120));
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, 120));
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 120, 120));
        jPanel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 120, 120));
        jPanel1.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 120));
        jPanel1.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 120, 120));
        jPanel1.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 120, 120));
        jPanel1.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 120, 120));
        jPanel1.add(chef2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 130));
        jPanel1.add(chef3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 130));
        jPanel1.add(chef4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 160, 130));
        jPanel1.add(chef5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 160, 130));
        jPanel1.add(estadoChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 330, 30));
        jPanel1.add(chefdurmiendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, 80));
        jPanel1.add(estadoJoey, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 240, 40));

        botonInicio.setText("Iniciar");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 23, 110, 40));

        chef1.setBackground(new java.awt.Color(255, 255, 255));
        chef1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productor.jpg"))); // NOI18N
        jPanel1.add(chef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 173, 159));

        joey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Consumidor.jpg"))); // NOI18N
        jPanel1.add(joey, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 192, 160));

        mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recursoCompartido.png"))); // NOI18N
        jPanel1.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 81, 700, 290));

        jButton1.setText("Agregar productor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jButton2.setText("Agregar consumidor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
        if (contadorProductores == 0 && contadorConsumidores == 0) {
            contadorProductores++;
            contadorConsumidores++;
            m = new ChefCliente(8, pizza0, pizza1, pizza2, pizza3, pizza4, pizza5, pizza6, pizza7, pizza8, estadoChef, estadoJoey, chefdurmiendo, c1, c2, c3, c4, c5, c6, c7, c8);
            Productor p1 = new Productor(m, 1);
            p1.start();

            Consumidor c1 = new Consumidor(m, 1);
            c1.start();
        } else {
            System.out.println("Ya esta corriendo el programa");
        }

    }//GEN-LAST:event_botonInicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImageIcon image = new ImageIcon(getClass().getResource("/imagenes/Productor.jpg"));
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(chef1.getWidth(), chef1.getHeight(), Image.SCALE_DEFAULT)
        );

        this.repaint();
        contadorProductores++;
        if (contadorProductores == 2) {
            chef2.setIcon(icon);
            Productor p2 = new Productor(m, 2);
            p2.start();
        }
        if (contadorProductores == 3) {
            chef3.setIcon(icon);
            Productor p3 = new Productor(m, 3);
            p3.start();
        }
        if (contadorProductores == 4) {
            chef4.setIcon(icon);
            Productor p4 = new Productor(m, 4);
            p4.start();
        }
        if (contadorProductores == 5) {
            chef5.setIcon(icon);
            Productor p5 = new Productor(m, 5);
            p5.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        contadorConsumidores++;
        if (contadorConsumidores == 2) {
            System.out.println(contadorConsumidores);
            Consumidor c2 = new Consumidor(m, 2);
            c2.start();
        }
        if (contadorConsumidores == 3) {
            System.out.println(contadorConsumidores);

            Consumidor c3 = new Consumidor(m, 3);
            c3.start();
        }
        if (contadorConsumidores == 4) {
            System.out.println(contadorConsumidores);

            Consumidor c4 = new Consumidor(m, 4);
            c4.start();
        }
        if (contadorConsumidores == 5) {
            System.out.println(contadorConsumidores);

            Consumidor c5 = new Consumidor(m, 5);
            c5.start();
        }
        if (contadorConsumidores == 6) {
            System.out.println(contadorConsumidores);

            Consumidor c6 = new Consumidor(m, 6);
            c6.start();
        }
        if (contadorConsumidores == 7) {
            System.out.println(contadorConsumidores);

            Consumidor c7 = new Consumidor(m, 7);
            c7.start();
        }
        if (contadorConsumidores == 8) {
            System.out.println(contadorConsumidores);

            Consumidor c8 = new Consumidor(m, 8);
            c8.start();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setImageLabel(JLabel chef1, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(chef1.getWidth(), chef1.getHeight(), Image.SCALE_DEFAULT)
        );
        chef1.setIcon(icon);

        this.repaint();
    }

    public void acomodarMesa(JLabel mesa, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(mesa.getWidth(), mesa.getHeight(), Image.SCALE_DEFAULT)
        );
        mesa.setIcon(icon);
        this.repaint();
    }

    public void consumidor(JLabel joey, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(joey.getWidth(), joey.getHeight(), Image.SCALE_DEFAULT)
        );
        joey.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel chef1;
    private javax.swing.JLabel chef2;
    private javax.swing.JLabel chef3;
    private javax.swing.JLabel chef4;
    private javax.swing.JLabel chef5;
    private javax.swing.JLabel chefdurmiendo;
    private javax.swing.JLabel estadoChef;
    private javax.swing.JLabel estadoJoey;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel joey;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel pizza0;
    private javax.swing.JLabel pizza1;
    private javax.swing.JLabel pizza2;
    private javax.swing.JLabel pizza3;
    private javax.swing.JLabel pizza4;
    private javax.swing.JLabel pizza5;
    private javax.swing.JLabel pizza6;
    private javax.swing.JLabel pizza7;
    private javax.swing.JLabel pizza8;
    // End of variables declaration//GEN-END:variables
}
